interface IExpertsData {
  id: number;
  name: string;
  role: string;
  description: string;
  imageUrl: string;
  profileUrl: string;
}

export const ExpertsData: IExpertsData[] = [
  {
    id: 1,
    name: 'Carol Harmer',
    role: 'Founder / Analyst at Charmer Trading',
    description: 'Chartered market technician',
    imageUrl: ' https://editorial.fxstreet.com/authors-input/carolHarmer.jpg',
    profileUrl: 'https://www.fxstreet.com/author/carol-harmer',
  },
  {
    id: 2,
    name: 'Ed Ponsi',
    role: 'Content Advisor FXStreet',
    description: 'Technical and fundamental hybrid analysis',
    imageUrl: 'https://editorial.fxstreet.com/authors/edPonsi.jpeg',
    profileUrl: 'https://www.fxstreet.com/author/ed-ponsi',
  },
  {
    id: 3,
    name: 'Kaia Parv',
    role: 'Senior Market Analyst',
    description: 'Fundamental & Technical Analysis',
    imageUrl: 'https://editorial.fxstreet.com/authors/kaiaParv.jpg',
    profileUrl: 'https://www.fxstreet.com/author/kaia-parv-cfa',
  },
  {
    id: 4,
    name: 'Sam Evans',
    role: 'Instructor Indipendent Analyst',
    description: 'Simplicity over complex indicators and strategies',
    imageUrl: 'https://editorial.fxstreet.com/authors/samEvans.jpg',
    profileUrl: 'https://www.fxstreet.com/author/sam-evans',
  },
  {
    id: 5,
    name: 'Sam Seiden',
    role: 'Trader Analyst & Educator',
    description: '',
    imageUrl: 'https://editorial.fxstreet.com/authors/samSeiden.jpg',
    profileUrl: 'https://www.fxstreet.com/author/sam-seiden',
  },
  {
    id: 6,
    name: 'Steve Ruffley',
    role: 'Owner SteveRuffley.com',
    description: 'Outright, swing, averaging, aggressive and intraday',
    imageUrl: 'https://editorial.fxstreet.com/authors/steveRuffley.png',
    profileUrl: 'https://www.fxstreet.com/author/steve-ruffley',
  },
  {
    id: 7,
    name: 'Gregor Horvat',
    role: 'Chief techinacal Strategiest at EW-Forcast',
    description: 'Elliott Wave short-term strategies',
    imageUrl: ' https://editorial.fxstreet.com/authors/gregorHorvat.jpg',
    profileUrl: 'https://www.fxstreet.com/author/gregor-horvat',
  },
  {
    id: 8,
    name: 'Navin Prithyani',
    role: 'Senior Trader at Forex Watchers',
    description: 'Price action, technical, swing',
    imageUrl: ' https://editorial.fxstreet.com/authors/navinPrithyani.png',
    profileUrl: 'https://www.fxstreet.com/author/navin-prithyani',
  },
  {
    id: 9,
    name: 'Sarid Harper',
    role: 'CTO at Pipnotic',
    description: 'Supply and demand, currency strength',
    imageUrl: ' https://editorial.fxstreet.com/authors/saridHarper.jpg',
    profileUrl: 'https://www.fxstreet.com/author/sarid-harper',
  },
  {
    id: 10,
    name: 'Dr. Woody Johnson',
    role: 'Trader',
    description: 'Psychology Instructor',
    imageUrl: 'https://editorial.fxstreet.com/authors/DrWoodyJohnson.jpg',
    profileUrl: 'https://www.fxstreet.com/author/dr-woody-johnson',
  },
  {
    id: 11,
    name: 'Alex Ong',
    role: 'Co-Founder at Traders Corner',
    description: 'Momentum trading',
    imageUrl: ' https://editorial.fxstreet.com/authors/alexOng.jpg',
    profileUrl: 'https://www.fxstreet.com/author/alex-ong',
  },
  {
    id: 12,
    name: 'David Pegler',
    role: 'Principal at Synergy Alliance Capital',
    description: 'Multiple time-frames, price action, fundamentals',
    imageUrl: ' https://editorial.fxstreet.com/authors/davidPegler.jpg',
    profileUrl: 'https://www.fxstreet.com/author/david-pegler',
  },
  {
    id: 13,
    name: 'Walter Peters',
    role: 'Trader and Owner of FXjake',
    description: 'Indicator-free trading systems',
    imageUrl: ' https://editorial.fxstreet.com/authors/walterPeters.jpg',
    profileUrl: 'https://www.fxstreet.com/author/walter-peters',
  },
  {
    id: 14,
    name: 'Jay Lakhani',
    role: 'Company Director at Bindal FX',
    description: 'Systems and Strategies',
    imageUrl: 'https://editorial.fxstreet.com/authors/jayLakhani.jpg',
    profileUrl: 'https://www.fxstreet.com/author/jay-lakhani',
  },
  {
    id: 15,
    name: 'Blake Morrow',
    role: 'Co-Founder/Analyst at Forex Analytix',
    description: 'Currency and equities strategist ',
    imageUrl: 'https://editorial.fxstreet.com/authors/blakeMorrow.jpg',
    profileUrl: 'https://www.fxstreet.com/author/blake-morrow',
  },
  {
    id: 16,
    name: 'Juan Alberto Maldonado',
    role: 'Analyst',
    description: 'Elliott Wave and Technical Analysis',
    imageUrl: 'https://editorial.fxstreet.com/authors/juanAlbertoMaldonado.jpg',
    profileUrl: 'https://www.fxstreet.com/author/juan-alberto-maldonado',
  },
  {
    id: 17,
    name: 'George Hallmey',
    role: 'Swing Trader',
    description: 'Intermarket Analysis',
    imageUrl: 'https://editorial.fxstreet.com/authors/georgeHallmey.png',
    profileUrl: 'https://www.fxstreet.com/author/george-hallmey',
  },
  {
    id: 18,
    name: 'Inna Rosputnia',
    role: 'Futures Trader',
    description: 'Financial Analyst',
    imageUrl: 'https://editorial.fxstreet.com/authors/innaRosputina.jpg',
    profileUrl: 'https://www.fxstreet.com/author/inna-rosputnia',
  },
];
